# Generated by Django 2.1 on 2018-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
