# Generated by Django 2.1.4 on 2018-12-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='prifle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
