# Generated by Django 2.1.4 on 2018-12-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181207_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='prile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.File'),
        ),
    ]
